apiVersion: apps/v1
kind: Deployment
metadata:
  name: workers-deployment
  labels:
    app: workers
spec:
  replicas: 1500
  selector:
    matchLabels:
      app: workers
  template:
    metadata:
      labels:
        app: workers
    spec:
      containers:
      - name: worker
        image: gcr.io/ossf-malware-analysis/analysis:latest
        imagePullPolicy: Always
        command: ["worker"]
        env:
        - name: OSSMALWARE_WORKER_SUBSCRIPTION
          value: gcppubsub://projects/ossf-malware-analysis/subscriptions/workers
        - name: OSSF_MALWARE_ANALYSIS_RESULTS
          value: gs://ossf-malware-analysis-results
        - name: OSSF_MALWARE_STATIC_ANALYSIS_RESULTS
          value: gs://ossf-malware-static-analysis-results
        - name: OSSF_MALWARE_ANALYSIS_FILE_WRITE_RESULTS
          value: gs://ossf-malware-analysis-file-write-results
        - name: LOGGER_ENV
          value: prod
        - name: OSSF_MALWARE_ANALYSIS_PACKAGES
          value: gs://ossf-malware-analysis-packages
        - name: OSSF_MALWARE_NOTIFICATION_TOPIC
          value: gcppubsub://projects/ossf-malware-analysis/topics/analysis-notify
        - name: OSSF_MALWARE_FEATURE_FLAGS
          value: ""
        securityContext:
          privileged: true
        volumeMounts:
          - mountPath: "/var/lib/containers"
            name: image-storage
          - mountPath: "/worker_tmp"
            name: worker-tmp
        resources:
          requests:
            cpu: 750m
            memory: 768Mi
          limits:
            cpu: 1
            memory: 2Gi
      volumes:
      - name: image-storage
        ephemeral:
          volumeClaimTemplate:
            metadata:
              labels:
                type: image-storage
            spec:
              accessModes:
              - ReadWriteOnce
              storageClassName: premium-rwo
              resources:
                requests:
                  storage: 20Gi
      - name: worker-tmp
        emptyDir:
          sizeLimit: 5Gi
  strategy:
    type: "RollingUpdate"
    rollingUpdate:
      maxUnavailable: "5%"
      maxSurge: "1%"
