apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: workers-set
  labels:
    app: workers
spec:
  serviceName: workers
  replicas: 5
  selector:
    matchLabels:
      app: workers
  template:
    metadata:
      labels:
        app: workers
    spec:
      containers:
      - name: worker
        image: gcr.io/ossf-malware-analysis/analysis:latest
        imagePullPolicy: Always
        command: ["worker"]
        env:
        - name: OSSMALWARE_WORKER_SUBSCRIPTION
          value: gcppubsub://projects/ossf-malware-analysis/subscriptions/workers
        - name: OSSF_MALWARE_ANALYSIS_RESULTS
          value: gs://ossf-malware-analysis-results
        - name: OSSMALWARE_DOCSTORE_URL
          value: firestore://projects/ossf-malware-analysis/databases/(default)/documents/
        - name: LOGGER_ENV
          value: prod
        securityContext:
          privileged: true
        volumeMounts:
          - mountPath: "/var/lib/containers"
            name: image-storage
        resources:
          requests:
            cpu: 500m
            memory: 512Mi
          limits:
            cpu: 1
            memory: 1Gi
  volumeClaimTemplates:
  - metadata:
      name: image-storage
    spec:
      accessModes:
        - ReadWriteOnce
      storageClassName: premium-rwo
      resources:
        requests:
          storage: 30Gi  
