version: "2"
run:
  concurrency: 6
linters:
  default: none
  enable:
    - asciicheck
    - bodyclose
    - copyloopvar
    - depguard
    - dogsled
    - errcheck
    - errorlint
    - exhaustive
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - godox
    - goheader
    - gomodguard
    - goprintffuncname
    - gosec
    - ineffassign
    - makezero
    - misspell
    - nakedret
    - nestif
    - noctx
    - nolintlint
    - predeclared
    - staticcheck
    - thelper
    - tparallel
    - unconvert
    - unparam
    - unused
    - whitespace
    - wrapcheck
  settings:
    errcheck:
      check-type-assertions: true
      check-blank: true
    exhaustive:
      default-signifies-exhaustive: true
    gocritic:
      enabled-checks:
        - appendAssign
        - badCond
        - caseOrder
        - codegenComment
        - commentedOutCode
        - deprecatedComment
        - dupBranchBody
        - dupCase
        - dupSubExpr
        - exitAfterDefer
        - flagName
        - nilValReturn
        - weakCond
        - octalLiteral
        - appendCombine
        - rangeExprCopy
        - rangeValCopy
        - boolExprSimplify
        - captLocal
        - commentFormatting
        - commentedOutImport
        - defaultCaseOrder
        - docStub
        - elseif
        - emptyFallthrough
        - hexLiteral
        - ifElseChain
        - methodExprCall
        - singleCaseSwitch
        - typeAssertChain
        - typeSwitchVar
        - underef
        - unlabelStmt
        - unlambda
    godox:
      keywords:
        - BUG
        - FIXME
        - HACK
    govet:
      enable:
        - fieldalignment
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  new-from-rev: HEAD
  new: true
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(github.com/ossf/package-analysis)
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
