version: "3"
services:
  zookeeper:
    image: confluentinc/cp-zookeeper@sha256:87314e87320abf190f0407bf1689f4827661fbb4d671a41cba62673b45b66bfa
    ports:
      - 2181:2181
    healthcheck:
      test: nc -z localhost 2181 || exit -1
      interval: 10s
      timeout: 5s
      retries: 3
    restart: on-failure
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_SYNC_LIMIT: 2

  kafka:
    image: confluentinc/cp-kafka@sha256:c6320f9a0cbf57075e102546de110dcebdf374955f12388d58c23a54b8a47d31
    ports:
      - 9094:9094
    depends_on:
      zookeeper:
        condition: service_healthy
    healthcheck:
      test: kafka-topics --bootstrap-server kafka:9092 --list
      interval: 30s
      timeout: 10s
      retries: 23
    restart: on-failure
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: INTERNAL://kafka:9092,OUTSIDE://kafka:9094
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:9092,OUTSIDE://localhost:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_offsets_topic_replication_factor: 1

  rustfs:
    image: rustfs/rustfs@sha256:378642b05b7dcb4849fb77ebe6aca4ced1c3f66e7e504247df95a5c9018d3358
    hostname: rustfs
    ports:
      - 9000:9000
      - 9001:9001
    restart: on-failure
    environment:
      RUSTFS_ACCESS_KEY: rustfs
      RUSTFS_SECRET_KEY: rustfs123
      RUSTFS_CONSOLE_ENABLE: true
      RUSTFS_CONSOLE_ADDRESS: :9001
      RUSTFS_ADDRESS: :9000
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/health/ready"]
      interval: 30s
      timeout: 20s
      retries: 3

  rustfs-create-buckets:
    image: rustfs/rc@sha256:9abd6fb2b41a38aad8e6efb4a47c308701ee72417962da2205ea4ec72e30a75f
    depends_on:
      rustfs:
        condition: service_healthy
    entrypoint: >
      /bin/sh -c "
      rc alias set local http://rustfs:9000 rustfs rustfs123;
      rc mb local/package-analysis-analyzed-packages;
      rc mb local/package-analysis-dynamic;
      rc mb local/package-analysis-execution-logs;
      rc mb local/package-analysis-file-writes;
      rc mb local/package-analysis-static || true;
      "

  analysis:
    image: gcr.io/ossf-malware-analysis/analysis:latest
    privileged: true
    ports:
      - 6060:6060
    restart: unless-stopped
    entrypoint: "/usr/local/bin/worker"
    cgroup: host
    environment:
      OSSMALWARE_WORKER_SUBSCRIPTION: kafka://worker?topic=workers
      OSSF_MALWARE_NOTIFICATION_TOPIC: kafka://notifications
      OSSF_MALWARE_ANALYZED_PACKAGES: s3://package-analysis-analyzed-packages?disable_https=true&use_path_style=true&endpoint=http://rustfs:9000
      OSSF_MALWARE_ANALYSIS_RESULTS: s3://package-analysis-dynamic?disable_https=true&use_path_style=true&endpoint=http://rustfs:9000
      OSSF_MALWARE_ANALYSIS_EXECUTION_LOGS: s3://package-analysis-execution-logs?disable_https=true&use_path_style=true&endpoint=http://rustfs:9000
      OSSF_MALWARE_ANALYSIS_FILE_WRITE_RESULTS: s3://package-analysis-file-writes?disable_https=true&use_path_style=true&endpoint=http://rustfs:9000
      OSSF_MALWARE_STATIC_ANALYSIS_RESULTS: s3://package-analysis-static?disable_https=true&use_path_style=true&endpoint=http://rustfs:9000
      OSSF_MALWARE_ANALYSIS_ENABLE_PROFILER: "true"
      OSSF_MALWARE_FEATURE_FLAGS: ""
      KAFKA_BROKERS: kafka:9092
      AWS_ACCESS_KEY_ID: rustfs
      AWS_SECRET_ACCESS_KEY: rustfs123
    depends_on:
      kafka:
        condition: service_healthy
      rustfs:
        condition: service_healthy

  scheduler:
    image: gcr.io/ossf-malware-analysis/scheduler:latest
    entrypoint: "/usr/local/bin/scheduler"
    depends_on:
      kafka:
        condition: service_healthy
    restart: on-failure
    environment:
      OSSMALWARE_WORKER_TOPIC: kafka://workers
      OSSMALWARE_SUBSCRIPTION_URL: kafka://worker?topic=package-feeds
      KAFKA_BROKERS: kafka:9092

  feeds:
    image: gcr.io/ossf-malware-analysis/scheduled-feeds:latest
    restart: on-failure
    ports:
      - 8080:8080
    depends_on:
      kafka:
        condition: service_healthy
    environment:
      PACKAGE_FEEDS_CONFIG_PATH: /config/feeds.yml
    user: "0"
    volumes:
      - "./config/:/config/"
