apiVersion: apps/v1
kind: Deployment
metadata:
  name: analysis-deployment
  labels:
    app: analysis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: analysis
  template:
    metadata:
      labels:
        app: analysis
    spec:
      containers:
      - name: app
        image: ko://github.com/ossf/package-analysis/analysis
        env:
          - name: OSSF_MALWARE_ANALYSIS_RESULTS
            value: gs://ossf-malware-analysis-results
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: analysis
spec:
  selector:
    app: analysis
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
