name: "Build"

on:
  pull_request:

permissions: read-all

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
    - uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6.5.0
      with:
        go-version-file: 'go.mod'
    - name: Install libpcap-dev
      run: sudo apt-get install -y libpcap-dev
    - run: go build -o scheduler ./cmd/scheduler
    - run: go build -o worker ./cmd/worker
    - run: go build -o analyze ./cmd/analyze
    - run: go build -o loader load.go
      working-directory: function/loader
    - run: go build -o staticanalyze staticanalyze.go
      working-directory: sandboxes/staticanalysis
