name: 'Dependency Review'

on:
  pull_request:
    paths-ignore:
      - '**.md'

permissions:
  contents: read

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@a12a3943b4bdde767164f792f33f40b04645d846
      - name: 'Dependency Review'
        uses: actions/dependency-review-action@284319451007d5ba938e4afb047f602d7f2cd6c6
