
name: 'Shellcheck'

on:
  push:
    paths:
      - '**.sh'

  pull_request:
    paths:
      - '**.sh'

permissions:
  contents: read

jobs:
  check-scripts:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: 'Check scripts in all directories'
        run: make check_scripts
