
name: 'Shellcheck'

on:
  push:
    paths:
      - '**.sh'

  pull_request:
    paths:
      - '**.sh'

permissions:
  contents: read

jobs:
  check-scripts:
    runs-on: ubuntu-latest
    steps:
      - name: 'Check scripts in all directories'
        run: make check_scripts
