
name: 'Shellcheck'

on:
  push:
    paths:
      - '**.sh'

  pull_request:
    paths:
      - '**.sh'

permissions:
  contents: read

jobs:
  check-scripts:
    runs-on: ubuntu-latest
    steps:
      - name: 'Check scripts in all directories'
        shell: bash
        # ensure there are actually .sh files in the repo before running shellcheck
        run: test -n '$(find -name "*.sh")' && shellcheck $(find -name "*.sh")
