
name: 'Shellcheck'

on:
  push:
    paths:
      - '**.sh'

  pull_request:
    paths:
      - '**.sh'

permissions:
  contents: read

jobs:
  check-scripts:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - name: 'Check scripts in all directories'
        run: make check_scripts
